blank_issues_enabled: false
issue_template:
  - name: ðŸ‘¾ Bug Report
    description: Report a bug or issue with the project.
    labels: ["bug"]
    template: bug_report.md
  - name: ðŸ’¡ Feature Request
    description: Create a new ticket for a new feature request.
    labels: ["enhancement"]
    template: feature_request.md
  - name: ðŸ“‹ Technical Workshop Preparation SOP
    description: Create a new ticket for preparing for a technical workshop.
    labels: ["documentation"]
    template: sop_workshop.md